title = "WebGPU Unleashed | A Practical Tutorial"
repo = "https://github.com/shi-yan/WebGPUTutorial"
# need to have the slash
prefix = "WebGPUTutorial"
target = "../WebGPUTutorial"
url = "https://shi-yan.github.io/"
meta_image = "meta.png"
description = "Your ticket to the dynamic world of graphics programming."
utilities = [ "utils" , "data", "shader", "crab_nebula"]
readme_folder = "readme"
default_sample = "4_02_reaction_diffusion"

[[content]]
title = "1. Basics"

[[content.sub_chapters]]
title = "1.0 Empty Canvas"
folder = "1_00_empty_canvas"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.1 Drawing a Triangle"
folder = "1_01_triangle"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.2 Drawing a Triangle with Defined Vertices"
folder = "1_02_triangle_with_vertices"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.3 Applying Hardcoded Vertex Colors"
folder = "1_03_vertex_color"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.4 Different Vertex Colors"
folder = "1_04_different_vertex_colors"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.5 Colored Triangle with a Single Buffer"
folder = "1_05_colored_triangle_with_a_single_buffer"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.6 Understanding Uniforms"
folder = "1_06_uniforms"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.7 Working with Textures"
folder = "1_07_working_with_textures"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.8 Utilizing Transformation Matrices"
folder = "1_08_transformation_matrices"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.9 Cameras"
folder = "1_09_cameras"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.10 Triangle Strips"
folder = "1_10_triangle_strips"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.11 Front and Back Faces"
folder = "1_11_front_and_back_faces"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.12 Depth"
folder = "1_12_depth"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.13 Indices"
folder = "1_13_indices"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.14 Loading Models"
folder = "1_14_loading_models"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.15 Normals"
folder = "1_15_normals"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.16 Lighting"

[[content.sub_chapters.sub_chapters]]
title = "1.16.1 Per-vertex Lighting"
folder = "1_16_1_lighting"
[[content.sub_chapters.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content.sub_chapters.sub_chapters]]
title = "1.16.2 Per-fragment Lighting"
folder = "1_16_2_lighting"
[[content.sub_chapters.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content.sub_chapters]]
title = "1.17 MSAA"
folder = "1_17_msaa"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.18 Mipmaps"

[[content.sub_chapters.sub_chapters]]
title = "1.18.1 Mipmaps 1"
folder = "1_18_1_mipmaps"
[[content.sub_chapters.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content.sub_chapters.sub_chapters]]
title = "1.18.2 Mipmaps 2"
folder = "1_18_2_mipmaps"
[[content.sub_chapters.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content]]
title = "2. 2D Techniques"

[[content.sub_chapters]]
title = "2.0 Render to Textures"
folder = "2_00_render_to_textures"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "2.1 Orthogonal Cameras"
folder = "2_01_orthogonal_cameras"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "2.2 Blur"

[[content.sub_chapters.sub_chapters]]
title = "2.2.1 Blur 1"
folder = "2_02_1_blur_1"
[[content.sub_chapters.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content.sub_chapters.sub_chapters]]
title = "2.2.2 Blur 2"
folder = "2_02_2_blur_2"
[[content.sub_chapters.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content.sub_chapters.sub_chapters]]
title = "2.2.3 Blur 3"
folder = "2_02_3_blur_3"
[[content.sub_chapters.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content.sub_chapters.sub_chapters]]
title = "2.2.4 Blur 4"
folder = "2_02_4_blur_4"
[[content.sub_chapters.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content.sub_chapters.sub_chapters]]
title = "2.2.5 Blur 5"
folder = "2_02_5_blur_5"
[[content.sub_chapters.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content.sub_chapters]]
title = "2.3 Video"

[[content.sub_chapters.sub_chapters]]
title = "2.3.1 Video 1"
folder = "2_03_1_video_1"
[[content.sub_chapters.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content.sub_chapters.sub_chapters]]
title = "2.3.2 Video 2"
folder = "2_03_2_video_2"
[[content.sub_chapters.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content.sub_chapters]]
title = "2.4 Text"
folder = "2_04_text"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "2.5 Billboard"
folder = "2_05_billboard"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "2.6 Fake 3D"
folder = "2_06_fake_3d"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content]]
title = "3. Control"

[[content.sub_chapters]]
title = "3.0 Canvas Resizing"
folder = "3_00_canvas_resizing"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "3.1 Arcball"
folder = "3_01_arcball"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "3.2 Picking"

[[content.sub_chapters.sub_chapters]]
title = "3.2.1 Ray Casting"
folder = "3_02_1_picking_ray_casting"
[[content.sub_chapters.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content.sub_chapters.sub_chapters]]
title = "3.2.2 Color Coding"
folder = "3_02_2_picking_color_coding"
[[content.sub_chapters.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content.sub_chapters]]
title = "3.3 Save Image and Video"
folder = "3_03_save_image_and_video"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "3.4 Worker"
folder = "3_04_worker"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false
[[content.sub_chapters.files]]
filename = "worker.js"
is_readonly = false

[[content.sub_chapters]]
title = "3.5 Error Handling and Limits"
folder = "3_05_error_handling_and_limits"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content]]
title = "4. Compute"

[[content.sub_chapters]]
title = "4.0 Prefix Sum"
folder = "4_00_prefix_sum"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "4.2 Reaction Diffusion"
folder = "4_02_reaction_diffusion"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content]]
title = "5. Advanced"

[[content.sub_chapters]]
title = "5.0 Stencil"
folder = "5_00_stencil"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "5.1 Shadow Maps"
folder = "5_01_shadow_maps"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "5.2 Toon Shading"
folder = "5_02_toon_shading"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "5.3 Equalrectangle Rendering"
folder = "5_03_equalrectangle_rendering"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "5.4 Mega Texture"
folder = "5_04_mega_texture"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "5.5 Transparency"
folder = "5_05_transparency"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "5.6 Skeleton Animation"
folder = "5_06_skeleton_animation"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "5.7 Bump Map"
folder = "5_07_bump_map"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false