title = "WGPU Tutorial"
repo = "https://github.com/shi-yan/WebGPUTutorial"
# need to have the slash
prefix = "WebGPUTutorial"
target = "../WebGPUTutorial"
url = "https://shi-yan.github.io/"
meta_image = "meta.png"
description = """
WebGPU example code."""
utilities = [ "utils" , "data", "shader"]

[[content]]
title = "1. Basics"

[[content.sub_chapters]]
title = "1.0 Empty Canvas"
folder = "1_0_empty_canvas"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.1 Drawing a Triangle"
folder = "1_1_triangle"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.2 Drawing a Triangle with Defined Vertices"
folder = "1_2_triangle_with_vertices"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.3 Applying Hardcoded Vertex Colors"
folder = "1_3_vertex_color"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.4 Different Vertex Colors"
folder = "1_4_different_vertex_colors"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.5 Colored Triangle with a Single Buffer"
folder = "1_5_colored_triangle_with_a_single_buffer"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.6 Understanding Uniforms"
folder = "1_6_uniforms"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.7 Working with Textures"
folder = "1_7_working_with_textures"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.8 Utilizing Transformation Matrices"
folder = "1_8_transformation_matrices"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.9 Cameras"
folder = "1_9_cameras"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.10 Triangle Strips"
folder = "1_10_triangle_strips"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.11 Front and Back Faces"
folder = "1_11_front_and_back_faces"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.12 Depth"
folder = "1_12_depth"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.13 Indices"
folder = "1_13_indices"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.14 Loading Models"
folder = "1_14_loading_models"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.15 Normals"
folder = "1_15_normals"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.16 Lighting"

[[content.sub_chapters.sub_chapters]]
title = "1.16.1 Per-vertex Lighting"
folder = "1_16_1_lighting"
[[content.sub_chapters.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content.sub_chapters.sub_chapters]]
title = "1.16.2 Per-fragment Lighting"
folder = "1_16_2_lighting"
[[content.sub_chapters.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content.sub_chapters]]
title = "1.17 MSAA"
folder = "1_17_msaa"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false

[[content.sub_chapters]]
title = "1.18 Mipmaps"

[[content.sub_chapters.sub_chapters]]
title = "1.18.1 Mipmaps 1"
folder = "1_18_1_mipmaps"
[[content.sub_chapters.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content.sub_chapters.sub_chapters]]
title = "1.18.2 Mipmaps 2"
folder = "1_18_2_mipmaps"
[[content.sub_chapters.sub_chapters.files]]
filename = "index.html"
is_readonly = true

[[content]]
title = "4. Advanced"

[[content.sub_chapters]]
title = "4.1 Shadow Maps"
folder = "4_1_shadow_maps"
[[content.sub_chapters.files]]
filename = "index.html"
is_readonly = false
